### ISSUE TITLE
The Steps & Implements of Algorithm

### ISSUE THREAD

**Issue by choupeiyuan** [GeneWu/MPDA#1]
![mpda](https://cloud.githubusercontent.com/assets/7425063/8369849/807b72ec-1bf2-11e5-9fac-4ba5a8c61ee9.png)

Hi, Gene. 
      I use a figure to shows all steps of the proposed algorithm, please check whether they are correct. and could you send me all your codes that can implement the whole process of the algorithm for the paper? 

Best Regards,
Peiyuan

**Comment by GeneWu** [comment]
Step 4 is implemented as an interactive interface. You should use the any simple implementation for equal frequency. I show you an example when creating a table to show the IR for a pair of continuous attributes. The first thing to do is to apply equal frequency to each of them. The number of bins parameter can be determined by rule of thumb. You should use the alpha to determine the number of bins. The alpha which is an integer can be from 2 to 6 (rule of thumb). The number of bins is the square root of the number of rows divided by the alpha. You can optimize the alpha by iterating its value to find the maximum classification accuracy after OCDD.

You can find the similar implementation here: (p.s. alpha is provided by the GUI and input by the user)
https://github.com/GeneWu/MPDA/blob/master/maca/src/mixedmodeaca/RCC.java#L202-L296
